### ISSUE TITLE
type error when using IORedis

### ISSUE THREAD

**Issue by jeanvdr** [anchan828/nest-session#1145]
Hi, 
I've got a type error when using IORedis:
Type 'Redis' is not assignable to type 'Client'.
  Type 'Redis' is missing the following properties from type 'Cluster': nodes, rpushBuffer, lpushBuffer, hsetBuffer, and 2 more.ts(2322)
redis-session.interface.d.ts(6, 5): The expected type comes from property 'redisClient' which is declared here on type 'RedisSessionModuleOptions'
Thanks

**Comment by anchan828** [comment]
See: https://github.com/tj/connect-redis/issues/359
